// src/app/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Button from '@/components/ui/Button'
import Input from '@/components/ui/Input'
import Card from '@/components/ui/Card'
import { generateGameCode } from '@/lib/utils'

export default function HomePage() {
  const [gameCode, setGameCode] = useState('')
  const [playerName, setPlayerName] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const router = useRouter()

  const createGame = async () => {
    setIsLoading(true)
    const code = generateGameCode()
    
    // Simulate loading delay
    await new Promise(resolve => setTimeout(resolve, 500))
    
    router.push(`/host/${code}` as any)
    setIsLoading(false)
  }

  const joinGame = async () => {
    if (!gameCode.trim() || !playerName.trim()) return
    
    setIsLoading(true)
    
    // Simulate validation delay
    await new Promise(resolve => setTimeout(resolve, 300))
    
    router.push(`/game/${gameCode.toUpperCase()}?name=${encodeURIComponent(playerName.trim())}` as any)
    setIsLoading(false)
  }

  const features = [
    {
      icon: '⚡',
      title: 'AI POWERED',
      description: 'Dynamic questions generated by AI'
    },
    {
      icon: '👥',
      title: 'MULTIPLAYER',
      description: 'Up to 10 players compete'
    },
    {
      icon: '🎮',
      title: 'STREAMER READY',
      description: 'Perfect for streamers'
    },
    {
      icon: '🏆',
      title: 'COMPETITIVE',
      description: 'Smart scoring system'
    }
  ]

  return (
    <div className="min-h-screen flex flex-col items-center justify-center p-8 relative">
      {/* Simple grid background */}
      <div className="absolute inset-0 opacity-20">
        <div className="absolute inset-0" style={{
          backgroundImage: `
            linear-gradient(rgba(255, 255, 255, 0.1) 1px, transparent 1px),
            linear-gradient(90deg, rgba(255, 255, 255, 0.1) 1px, transparent 1px)
          `,
          backgroundSize: '32px 32px'
        }} />
      </div>

      <div className="w-full max-w-6xl relative z-10">
        {/* Hero Section */}
        <div className="text-center mb-16 pixel-bounce">
          <div className="text-[80px] mb-8">🧠</div>
          <h1 className="text-[40px] md:text-[48px] font-bold text-white mb-8 gradient-text uppercase tracking-wider">
            AI QUIZ PLATFORM
          </h1>
          <p className="text-[16px] md:text-[18px] text-green-400 mb-12 max-w-4xl mx-auto font-bold uppercase tracking-wide leading-relaxed">
            &gt; THE ULTIMATE MULTIPLAYER TRIVIA EXPERIENCE &lt;<br/>
            &gt; POWERED BY ARTIFICIAL INTELLIGENCE &lt;<br/>
            &gt; PERFECT FOR STREAMERS AND COMPETITIVE FUN &lt;
          </p>
        </div>

        {/* Main Actions */}
        <div className="grid md:grid-cols-2 gap-12 mb-20">
          {/* Host Game */}
          <Card variant="default" className="text-center pixel-slide-up">
            <div className="text-[64px] mb-6">🎮</div>
            <h2 className="text-[20px] font-bold text-white mb-6 uppercase tracking-wider">HOST GAME</h2>
            <p className="text-[12px] text-gray-300 mb-8 uppercase tracking-wide leading-relaxed">
              &gt; CREATE NEW GAME ROOM<br/>
              &gt; INVITE PLAYERS TO JOIN<br/>
              &gt; CONTROL THE SESSION
            </p>
            <Button
              onClick={createGame}
              loading={isLoading}
              variant="primary"
              size="xl"
              className="w-full"
            >
              {isLoading ? 'LOADING...' : 'CREATE GAME'}
            </Button>
          </Card>

          {/* Join Game */}
          <Card variant="default" className="text-center pixel-slide-up">
            <div className="text-[64px] mb-6">🚀</div>
            <h2 className="text-[20px] font-bold text-white mb-6 uppercase tracking-wider">JOIN GAME</h2>
            <div className="space-y-6 mb-8">
              <Input
                placeholder="ENTER YOUR NAME"
                value={playerName}
                onChange={(e) => setPlayerName(e.target.value)}
                maxLength={20}
              />
              <Input
                placeholder="GAME CODE (ABC123)"
                value={gameCode}
                onChange={(e) => setGameCode(e.target.value.toUpperCase())}
                maxLength={6}
              />
            </div>
            <Button
              onClick={joinGame}
              loading={isLoading}
              disabled={!gameCode.trim() || !playerName.trim()}
              variant="secondary"
              size="xl"
              className="w-full"
            >
              {isLoading ? 'JOINING...' : 'JOIN GAME'}
            </Button>
          </Card>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8 mb-16">
          {features.map((feature, index) => (
            <div 
              key={index} 
              className="pixel-slide-up" 
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              <Card variant="glass" className="text-center h-full">
                <div className="text-[48px] mb-4 text-yellow-400">
                  {feature.icon}
                </div>
                <h3 className="text-[14px] font-bold text-white mb-4 uppercase tracking-wider">{feature.title}</h3>
                <p className="text-[10px] text-gray-300 uppercase tracking-wide leading-relaxed">{feature.description}</p>
              </Card>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="text-center text-gray-400 text-[12px] uppercase tracking-wider font-bold">
          <div className="mb-4 text-green-400">
            [ SYSTEM STATUS: ONLINE ]
          </div>
          <p>&gt; PERFECT FOR STREAMERS &lt; COMPETITIVE SCORING &gt; AI-GENERATED CONTENT &lt;</p>
        </div>
      </div>
    </div>
  )
}