// src/components/ui/Card.stories.ts
import type { Meta, StoryObj } from '@storybook/react'
import Card from './Card'
import Button from './Button'
import Input from './Input'

const meta = {
  title: 'UI/Card',
  component: Card,
  parameters: {
    layout: 'centered',
    backgrounds: {
      default: 'pixel-dark',
      values: [
        { name: 'pixel-dark', value: '#000000' },
        { name: 'pixel-gray', value: '#222222' },
      ],
    },
  },
  tags: ['autodocs'],
  argTypes: {
    variant: {
      control: { type: 'select' },
      options: ['default', 'glass', 'solid'],
    },
  },
} satisfies Meta<typeof Card>

export default meta
type Story = StoryObj<typeof meta>

export const Default: Story = {
  args: {
    children: (
      <div>
        <h3 className="text-[18px] font-bold text-white mb-4 uppercase">DEFAULT CARD</h3>
        <p className="text-[12px] text-gray-300 uppercase tracking-wide">
          THIS IS A DEFAULT CARD WITH PIXEL ART STYLING.
        </p>
      </div>
    ),
  },
}

export const Glass: Story = {
  args: {
    variant: 'glass',
    children: (
      <div>
        <h3 className="text-[18px] font-bold text-white mb-4 uppercase">GLASS CARD</h3>
        <p className="text-[12px] text-gray-300 uppercase tracking-wide">
          THIS CARD HAS A GLASS VARIANT STYLING.
        </p>
      </div>
    ),
  },
}

export const Solid: Story = {
  args: {
    variant: 'solid',
    children: (
      <div>
        <h3 className="text-[18px] font-bold text-white mb-4 uppercase">SOLID CARD</h3>
        <p className="text-[12px] text-gray-300 uppercase tracking-wide">
          THIS IS A SOLID CARD VARIANT.
        </p>
      </div>
    ),
  },
}

export const GameHostCard: Story = {
  args: {
    variant: 'default',
    children: (
      <div className="text-center max-w-sm">
        <div className="text-[64px] mb-6">🎮</div>
        <h2 className="text-[20px] font-bold text-white mb-6 uppercase tracking-wider">HOST GAME</h2>
        <p className="text-[12px] text-gray-300 mb-8 uppercase tracking-wide leading-relaxed">
          &gt; CREATE NEW GAME ROOM<br/>
          &gt; INVITE PLAYERS TO JOIN<br/>
          &gt; CONTROL THE SESSION
        </p>
        <Button variant="primary" size="xl" className="w-full">
          CREATE GAME
        </Button>
      </div>
    ),
  },
}

export const GameJoinCard: Story = {
  args: {
    variant: 'default',
    children: (
      <div className="text-center max-w-sm">
        <div className="text-[64px] mb-6">🚀</div>
        <h2 className="text-[20px] font-bold text-white mb-6 uppercase tracking-wider">JOIN GAME</h2>
        <div className="space-y-6 mb-8">
          <Input placeholder="ENTER YOUR NAME" />
          <Input placeholder="GAME CODE (ABC123)" />
        </div>
        <Button variant="secondary" size="xl" className="w-full">
          JOIN GAME
        </Button>
      </div>
    ),
  },
}

export const FeatureCard: Story = {
  args: {
    variant: 'glass',
    children: (
      <div className="text-center max-w-xs">
        <div className="text-[48px] mb-4 text-yellow-400">⚡</div>
        <h3 className="text-[14px] font-bold text-white mb-4 uppercase tracking-wider">AI POWERED</h3>
        <p className="text-[10px] text-gray-300 uppercase tracking-wide leading-relaxed">
          DYNAMIC QUESTIONS GENERATED BY AI
        </p>
      </div>
    ),
  },
}

export const PlayerStatsCard: Story = {
  args: {
    variant: 'solid',
    children: (
      <div className="max-w-xs">
        <div className="text-center mb-6">
          <div className="text-[48px] mb-2">👑</div>
          <h3 className="text-[18px] font-bold text-white uppercase tracking-wider">PLAYER STATS</h3>
        </div>
        <div className="space-y-3">
          <div className="flex justify-between text-[12px] uppercase">
            <span className="text-gray-300">GAMES PLAYED:</span>
            <span className="text-white font-bold">42</span>
          </div>
          <div className="flex justify-between text-[12px] uppercase">
            <span className="text-gray-300">BEST SCORE:</span>
            <span className="text-white font-bold">9,500</span>
          </div>
          <div className="flex justify-between text-[12px] uppercase">
            <span className="text-gray-300">WIN RATE:</span>
            <span className="text-white font-bold">73%</span>
          </div>
        </div>
      </div>
    ),
  },
}

export const AllVariants: Story = {
  args: {
    children: null, // Required by TypeScript but not used in render
  },
  render: () => (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-8 p-8">
      <Card variant="default">
        <h3 className="text-[16px] font-bold text-white mb-3 uppercase">DEFAULT</h3>
        <p className="text-[12px] text-gray-300 uppercase">Default card styling</p>
      </Card>
      <Card variant="glass">
        <h3 className="text-[16px] font-bold text-white mb-3 uppercase">GLASS</h3>
        <p className="text-[12px] text-gray-300 uppercase">Glass variant styling</p>
      </Card>
      <Card variant="solid">
        <h3 className="text-[16px] font-bold text-white mb-3 uppercase">SOLID</h3>
        <p className="text-[12px] text-gray-300 uppercase">Solid variant styling</p>
      </Card>
    </div>
  ),
}